name: 'Publish Markdown As PDF'
description: 'Publish a group of Markdown documents as a single PDF document'
author: 'Samuel Ryan <sam@samryan.co.uk>'
inputs:
  sources:
    description: 'List of glob patterns to Markdown files in order of their inclusion in the PDF'
    required: true
  images_dir:
    description: 'the directory holding all referenced images.'
    required: false
  image_import:
    description: 'the base path string used in the md files to reference images.'
    required: false
outputs:
  pdf:
    description: Published PDF Document
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sources }}
    - ${{ inputs.images_dir }}
    - ${{ inputs.image_import }}
branding:
  icon: 'file-text'
  color: 'green'
